import Foundation

struct Session: Codable, Identifiable, Equatable {
    let name: String
    let active: Bool
    var working: Bool
    var unread: Int
    /// Coding agent holding the pane ("claude", …); empty = bare shell.
    var agent: String
    /// Classified project of the pane's working directory (longest path-prefix
    /// match on the server); empty = unclassified. Drives profile attribution.
    var project: String
    var id: String { name }

    init(name: String, active: Bool, working: Bool = false, unread: Int = 0, agent: String = "", project: String = "") {
        self.name = name
        self.active = active
        self.working = working
        self.unread = unread
        self.agent = agent
        self.project = project
    }

    private enum CodingKeys: String, CodingKey { case name, active, working, unread, agent, project }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        name = try c.decode(String.self, forKey: .name)
        active = try c.decode(Bool.self, forKey: .active)
        // working/unread/agent/project are omitempty on the server →
        // decodeIfPresent for backward compatibility with payloads that omit them.
        working = try c.decodeIfPresent(Bool.self, forKey: .working) ?? false
        unread = try c.decodeIfPresent(Int.self, forKey: .unread) ?? 0
        agent = try c.decodeIfPresent(String.self, forKey: .agent) ?? ""
        project = try c.decodeIfPresent(String.self, forKey: .project) ?? ""
    }
}

// Posted by ChatViewModel when a session_state WS event arrives, so the
// Sessions list can update working/unread in real time without polling.
extension Notification.Name {
    static let sessionStateChanged = Notification.Name("makro.sessionStateChanged")
}

struct ChatMessage: Identifiable, Equatable {
    enum Role: String, Codable {
        case user, assistant, system
    }

    let id: UUID
    let role: Role
    var text: String
    let timestamp: Date
    /// 随消息发送的附件（wf_3310501a9fe4）。本地渲染用 name/mime；重开
    /// transcript 后无缩略图数据，显示占位 chip（原图在服务端常驻）。
    var attachments: [ChatAttachment]?

    init(id: UUID = UUID(), role: Role, text: String, timestamp: Date = Date(), attachments: [ChatAttachment]? = nil) {
        self.id = id
        self.role = role
        self.text = text
        self.timestamp = timestamp
        self.attachments = attachments
    }
}

/// Chat 附件元数据（wf_3310501a9fe4）：上传后由服务端回填 id/path；
/// thumbnail 仅待发托盘/刚发送的气泡持有（不持久化，transcript 只存元数据）。
struct ChatAttachment: Codable, Equatable, Identifiable {
    let id: String
    let name: String
    let mime: String
    let bytes: Int
    let path: String?

    enum CodingKeys: String, CodingKey { case id, name, mime, bytes, path }
}

// 开单对话收敛出的计划（09-29）：等用户确认的 brief 预览卡。经 `plan` WS
// 事件下发；确认/取消走 /api/chat/intake/confirm|deny——服务端 startTask
// 正门开单，对话本身不执行任何东西。0930 起带落点（路由层判定，计划卡
// 显示；pinnedSession=用户对话中钉住的转述）。
struct PendingPlan: Codable, Equatable {
    let title: String    // 一句话标题（开单后的 workflow title）
    let summary: String  // 一句话概述
    let brief: String    // 完整 brief（背景/要做什么/产出/时限等已确认事实）
    let pinnedSession: String?
    let landing: Landing?

    struct Landing: Codable, Equatable {
        let session: String
        let note: String
    }
}

enum ConnectionState: Equatable {
    case disconnected
    case connecting
    case connected
}

// A discoverable artifact (HTML page or video) generated by an AI agent,
// surfaced from the agent's session working directory.
struct Artifact: Codable, Identifiable, Equatable {
    let session: String // owning tmux session (central-store tag)
    let name: String    // basename
    let path: String    // relative to session cwd
    let type: String    // "html" or "video"
    let mtime: Int64    // unix seconds
    let size: Int64     // bytes
    /// Ledger id (server artifacts table) — present for juli store artifacts,
    /// nil for legacy makro central-store files. Required by
    /// POST /api/artifact/share {id}; nil artifacts are not shareable.
    let ledgerId: String?

    // Cross-session uniqueness: two sessions can both have "report.html".
    var id: String { ledgerId ?? "\(session)/\(path)" }
    var isHTML: Bool { type == "html" }
    var isVideo: Bool { type == "video" }

    // 多格式富文本查看（wf_b93d083f6682，2026-10-05）：按文件后缀判定，
    // 不依赖服务端 type（服务端 md/json 都归 text/plain，区分不了）。
    private var lowerName: String { name.lowercased() }
    var isMarkdown: Bool { lowerName.hasSuffix(".md") || lowerName.hasSuffix(".markdown") }
    var isJSON: Bool { lowerName.hasSuffix(".json") }
    var isImage: Bool {
        [".png", ".jpg", ".jpeg", ".gif", ".webp"].contains { lowerName.hasSuffix($0) }
    }
    var isPDF: Bool { lowerName.hasSuffix(".pdf") }
    var isOffice: Bool {
        [".pptx", ".ppt", ".docx", ".doc", ".xlsx", ".xls", ".potx"].contains { lowerName.hasSuffix($0) }
    }
    var isZipLike: Bool { [".zip", ".gz", ".tar", ".7z"].contains { lowerName.hasSuffix($0) } }
    var isTextLike: Bool {
        [".txt", ".log", ".csv", ".yaml", ".yml", ".xml", ".svg", ".plist", ".ini", ".conf"]
            .contains { lowerName.hasSuffix($0) }
    }

    // 所属单（wf_1bc08ecd4184，方案 A 服务端 join）：卡片芯片与预览页「所属单」
    // 横幅的数据源——legacy makro 文件无此键，解码为 nil 容错。
    var workflow: ArtifactWorkflowRef? { _workflow }
    private var _workflow: ArtifactWorkflowRef?

    private enum CodingKeys: String, CodingKey {
        case session, name, path, type, mtime, size
        case ledgerId = "id"
        case _workflow = "workflow"
    }

    init(session: String, name: String, path: String, type: String,
         mtime: Int64, size: Int64, ledgerId: String? = nil, workflow: ArtifactWorkflowRef? = nil) {
        self.session = session; self.name = name; self.path = path; self.type = type
        self.mtime = mtime; self.size = size; self.ledgerId = ledgerId
        self._workflow = workflow
    }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        session = try c.decode(String.self, forKey: .session)
        name = try c.decode(String.self, forKey: .name)
        path = try c.decode(String.self, forKey: .path)
        type = try c.decode(String.self, forKey: .type)
        mtime = try c.decode(Int64.self, forKey: .mtime)
        size = try c.decode(Int64.self, forKey: .size)
        ledgerId = try c.decodeIfPresent(String.self, forKey: .ledgerId)
        _workflow = try c.decodeIfPresent(ArtifactWorkflowRef.self, forKey: ._workflow)
    }
}

/// Artifact 的所属单摘要（服务端 /api/artifacts join 附带，wf_1bc08ecd4184）。
struct ArtifactWorkflowRef: Codable, Equatable {
    let id: String
    let title: String
    let status: String
}

// MARK: - Lifecycle (V2 pipeline)

struct LifecycleWorkflow: Codable, Identifiable, Equatable {
    let id: String
    let kind: String
    let title: String
    let status: String
    var project: String?
    var session: String?
    let created_at: String
    let updated_at: String
    var prompt_count: Int?
    var waiting_steps: Int?
    /// 单子级免批（2026-10-07）：true=非发送闸门自动批准（服务端一等字段）。
    var auto_approve: Bool?
    /// Raw workflow meta (assigned_session lives here — the human's routing
    /// decision for the case). Values decode tolerantly: non-strings become
    /// .other so numeric fields (uid) never break the whole workflow decode.
    var meta: [String: WorkflowMetaValue]?
}

enum WorkflowMetaValue: Codable, Equatable {
    case string(String)
    case number(Double)
    case other

    init(from decoder: Decoder) throws {
        let c = try decoder.singleValueContainer()
        if let s = try? c.decode(String.self) {
            self = .string(s)
        } else if let d = try? c.decode(Double.self) {
            self = .number(d)
        } else {
            self = .other
        }
    }

    func encode(to encoder: Encoder) throws {
        var c = encoder.singleValueContainer()
        switch self {
        case .string(let s): try c.encode(s)
        case .number(let d): try c.encode(d)
        case .other: try c.encodeNil()
        }
    }

    var stringValue: String? {
        if case .string(let s) = self { return s }
        return nil
    }

    var intValue: Int? {
        if case .number(let d) = self, d == d.rounded() { return Int(d) }
        return nil
    }
}

struct LifecycleStep: Codable, Identifiable, Equatable {
    let id: String
    let workflow_id: String
    let seq: Int
    let kind: String
    var title: String?
    let status: String
    var input: [String: JSONValue]?
    var output: [String: JSONValue]?
    let updated_at: String
    /// 节点时序真数据（离开 pending / 到达终态的首次时刻）；未开跑时
    /// 服务端省略字段。created_at 沿用旧口径（=updated_at），勿用作开始时间。
    var started_at: String?
    var completed_at: String?
    var summary: String?

    var isGate: Bool { kind == "gate" }
    var isWaiting: Bool { status == "waiting_human" }
    var displayTitle: String { title ?? kind }

    /// 紧凑耗时：到终态→"Xm"；在途→"Xm…"；未开跑→nil。
    var timingLabel: String? {
        guard let start = started_at.flatMap(MakroISO.date(from:)) else { return nil }
        let end = completed_at.flatMap(MakroISO.date(from:)) ?? Date()
        let sec = max(0, Int(end.timeIntervalSince(start)))
        let done = completed_at != nil
        if sec < 60 { return done ? "\(sec)s" : "\(sec)s…" }
        let m = sec / 60
        if m < 60 { return done ? "\(m)m" : "\(m)m…" }
        return done ? "\(m / 60)h\(m % 60)m" : "\(m / 60)h\(m % 60)m…"
    }
}

/// A waiting gate + its owning workflow, as /api/lifecycle/steps returns.
struct GateQueueItem: Codable, Identifiable, Equatable {
    struct WFRef: Codable, Equatable {
        let id: String
        let title: String
        let kind: String
        let status: String
    }
    let step: LifecycleStep
    let workflow: WFRef?

    var id: String { step.id }
}

/// Workflow detail tree from /api/lifecycle/workflows/{id}.
/// Workflow detail tree from /api/lifecycle/workflows/{id}. The server also
/// returns `runs: [{run, prompts}]` — deliberately not modeled: nothing here
/// consumes it, and a mismatched shape must never break the whole decode
/// (that exact bug blanked the detail sheet for every case with runs).
struct LifecycleWorkflowTree: Codable, Equatable {
    let workflow: LifecycleWorkflow
    var steps: [LifecycleStep]?
    /// 该单窗口内其会话的 claude_code 回合聚合（wf_2542c2c7eb13：
    /// Round 语义澄清=Prompt 数而非 Workflow 数）。旧引擎不返回则解码 nil。
    var promptStats: PromptStats?
    /// API 等效价格（wf_535149a174fe）：同窗口用量代入智谱 bigmodel 价目。
    /// 旧引擎不返回则解码 nil。
    var usageCost: UsageCost?
}

struct PromptStats: Codable, Equatable {
    let count: Int
    let inputTokens: Double
    let outputTokens: Double
}

/// 「这单走 API 要花多少钱」：cache/input/output 三价分别计价加总
/// （元；cached 是 input 子集——cache 价 × cached + input 价 × 差额）。
/// 不在价目内的模型 priced=false：只显用量，绝不猜价。
struct UsageCost: Codable, Equatable {
    struct Cost: Codable, Equatable {
        let cache: Double
        let input: Double
        let output: Double
        let total: Double
    }
    struct ModelCost: Codable, Equatable {
        let model: String      // 账本原样名（对账用）
        let label: String      // 价目展示名
        let free: Bool
        let priced: Bool
        let calls: Int
        let inputTokens: Double   // 含缓存（展示口径同 promptStats）
        let cachedTokens: Double
        let inputTokensChargeable: Double
        let outputTokens: Double
        let tiersHit: [String]?
        let costCny: Cost
    }
    let currency: String   // "CNY"
    let unit: String       // "per_1m_tokens"
    let pricingSource: String?
    let pricingRetrievedAt: String?
    let byModel: [ModelCost]
    let totalCny: Cost
    let unpricedModels: [String]?
}

/// 费用分析聚合（wf_6a74fc4a23e4，GET /api/lifecycle/cost-stats）：范围内
/// workflows 逐单复用详情 usageCost 口径后的 Flow 层聚合。分桶右开区间
///（[0,5)[5,20)[20,50)[50,100)[100,200)[200+)，服务端单一定义）。
struct CostStats: Codable, Equatable {
    struct Overall: Codable, Equatable {
        let workflows: Int
        let ordersWithCost: Int
        let zeroCostOrders: Int
        let totalCny: Double
        let meanCny: Double
        let medianCny: Double
        let p90Cny: Double
        let maxCny: Double
    }
    struct BucketModel: Codable, Equatable {
        let model: String
        let label: String
        let count: Int
        let totalCny: Double
    }
    struct Bucket: Codable, Equatable {
        let label: String
        let edges: [Double?]   // [lo, hi]；hi=nil 表示 ¥lo+ 开口桶
        let count: Int
        let totalCny: Double
        let byModel: [BucketModel]
    }
    struct PerOrder: Codable, Equatable {
        let id: String
        let title: String
        let kind: String
        let status: String
        let createdAt: String
        let prompts: Int
        let totalCny: Double
        let models: [String]
    }
    struct ModelAgg: Codable, Equatable {
        let model: String
        let label: String
        let orders: Int
        let totalCny: Double
    }
    let days: Int
    let since: String?
    let pricingRetrievedAt: String?
    let overall: Overall
    let buckets: [Bucket]
    let perOrder: [PerOrder]
    let models: [ModelAgg]
    let unpricedOrders: [String]?
}

// One immutable version in a case's evidence chain (server artifacts table).
struct CaseArtifact: Codable, Identifiable, Equatable {
    let id: String
    let workflow_id: String
    let role: String // intake_attachment | agent_output | draft_attachment
    let name: String
    let seq: Int
    var mime: String?
    let bytes: Int64
    var sha256: String?
    var session: String?
    var storage: ArtifactStorageInfo?
    var created_at: String?
    var deleted_at: String?

    struct ArtifactStorageInfo: Codable, Equatable {
        var backend: String?
    }

    var isPurged: Bool { deleted_at != nil && !(deleted_at ?? "").isEmpty }
    var hasBytes: Bool {
        // "none" backend = identity-only fact (oversize); purged = bytes gone.
        !isPurged && storage?.backend != "none"
    }
    var roleLabel: String {
        switch role {
        case "intake_attachment": return "Inbound attachment"
        case "agent_output": return "Execution output"
        case "draft_attachment": return "Reply attachment"
        case "case_journey": return "Closing flow"
        default: return role
        }
    }
}

/// JSON value wrapper for step input/output maps. Steps stash structured
/// payload here (gate `checks`, `deliverables`, agent `session`, `error`),
/// so the wrapper keeps enough shape to walk one level of nesting.
struct JSONValue: Codable, Equatable {
    let stringValue: String?
    let numberValue: Double?
    let boolValue: Bool?
    let arrayValue: [JSONValue]?
    let dictValue: [String: JSONValue]?

    init(from decoder: Decoder) throws {
        let c = try decoder.singleValueContainer()
        if let s = try? c.decode(String.self) {
            stringValue = s; numberValue = nil; boolValue = nil; arrayValue = nil; dictValue = nil
        } else if let b = try? c.decode(Bool.self) {
            stringValue = nil; numberValue = nil; boolValue = b; arrayValue = nil; dictValue = nil
        } else if let d = try? c.decode(Double.self) {
            stringValue = nil; numberValue = d; boolValue = nil; arrayValue = nil; dictValue = nil
        } else if let a = try? c.decode([JSONValue].self) {
            stringValue = nil; numberValue = nil; boolValue = nil; arrayValue = a; dictValue = nil
        } else if let o = try? c.decode([String: JSONValue].self) {
            stringValue = nil; numberValue = nil; boolValue = nil; arrayValue = nil; dictValue = o
        } else {
            stringValue = nil; numberValue = nil; boolValue = nil; arrayValue = nil; dictValue = nil
        }
    }

    func encode(to encoder: Encoder) throws {
        var c = encoder.singleValueContainer()
        if let v = stringValue { try c.encode(v) }
        else if let v = boolValue { try c.encode(v) }
        else if let v = numberValue { try c.encode(v) }
        else if let v = arrayValue { try c.encode(v) }
        else if let v = dictValue { try c.encode(v) }
        else { try c.encodeNil() }
    }

    init(string: String) {
        stringValue = string; numberValue = nil; boolValue = nil; arrayValue = nil; dictValue = nil
    }

    var isEmpty: Bool {
        stringValue == nil && numberValue == nil && boolValue == nil
            && (arrayValue == nil || arrayValue?.isEmpty == true)
            && (dictValue == nil || dictValue?.isEmpty == true)
    }
}

// MARK: - Gate payload helpers (server shapes: sendChecks.ts / deliverables)

/// One send-preflight check on a waiting gate: `input.checks[]`.
struct GateCheck: Equatable {
    let name: String
    let status: String // pass | warn | fail
    var detail: String?

    var failed: Bool { status == "fail" }
}

/// Delivery pointer shown on a gate: `deliverables[]` (input or output).
/// `id` addresses the artifact store (fetchable via /api/artifacts/:id/content);
/// view_role "body" marks the email body being approved.
struct GateDeliverable: Equatable {
    let name: String
    var id: String?
    var viewRole: String?
    var summary: String?
    var bytes: Int64?
}

extension LifecycleStep {
    var checkItems: [GateCheck] {
        guard let arr = input?["checks"]?.arrayValue else { return [] }
        return arr.map { v in
            let d = v.dictValue
            return GateCheck(
                name: d?["name"]?.stringValue ?? "?",
                status: d?["status"]?.stringValue ?? "?",
                detail: d?["detail"]?.stringValue
            )
        }
    }

    var hasFailedCheck: Bool { checkItems.contains(where: \.failed) }

    var deliverableItems: [GateDeliverable] {
        let arr = input?["deliverables"]?.arrayValue ?? output?["deliverables"]?.arrayValue ?? []
        return arr.map { v in
            let d = v.dictValue
            var item = GateDeliverable(name: d?["name"]?.stringValue ?? "?", id: nil, viewRole: nil, summary: nil, bytes: nil)
            item.id = d?["id"]?.stringValue
            item.viewRole = d?["view_role"]?.stringValue
            item.summary = d?["summary"]?.stringValue
            if let b = d?["bytes"]?.numberValue { item.bytes = Int64(b) }
            return item
        }
    }

    /// 内联正文（body_source:inline 的邮件稿）。
    var bodyInline: String? {
        guard let b = input?["body"]?.stringValue, !b.isEmpty else { return nil }
        return b
    }

    /// 正文契约路径：body_ref → 工件按 id 取字节、按哈希核验。
    var bodyRef: (id: String, name: String)? {
        guard let d = input?["body_ref"]?.dictValue,
              let id = d["id"]?.stringValue, !id.isEmpty else { return nil }
        return (id, d["name"]?.stringValue ?? "Body")
    }

    /// Server stashes the failure reason on `output.error` (engine.go / capabilities).
    var outputError: String? {
        guard let e = output?["error"]?.stringValue, !e.isEmpty else { return nil }
        return e
    }

    /// The tmux session this step runs in: seeded into agent/verify input by
    /// gate approve; falls back to the workflow's session / assigned_session.
    /// 发送回执（send 步 output：to/sent_at + 随信附件清单）。
    var sendReceipt: (to: String, sentAt: String?, attachments: [String])? {
        guard kind == "send", status == "completed",
              let to = output?["to"]?.stringValue, !to.isEmpty else { return nil }
        let atts = (output?["attachments"]?.arrayValue ?? []).compactMap { a in
            a.dictValue?["name"]?.stringValue ?? a.stringValue
        }
        return (to, output?["sent_at"]?.stringValue, atts)
    }

    /// 无契约 fallback 正文：body_ref/deliverables 都缺席时，正文可能只
    /// 以 output.body / output.draft / output.output 内联存在——审批卡的
    /// 最后防线，保证"点 OK 前看得到内容"永远有东西可看。
    var fallbackBody: String? {
        for key in ["body", "draft", "output"] {
            if let v = output?[key]?.stringValue, v.count > 40 { return v }
        }
        for key in ["body", "draft"] {
            if let v = input?[key]?.stringValue, v.count > 40 { return v }
        }
        return nil
    }

    func sessionName(in workflow: LifecycleWorkflow) -> String? {
        let s = input?["session"]?.stringValue
            ?? workflow.session
            ?? workflow.meta?["assigned_session"]?.stringValue
        return (s?.isEmpty == false) ? s : nil
    }
}

// ── 技能目录（GET /api/skills，2026-10-02 追溯一期）─────────────────────────
// 家族/用途/分发健康（sync-skills 四落点）+ skill_used 账本事件的用量聚合。
// uses=0 是真实口径（无事件不伪造）；resident=常驻类（宪法每任务卡必载，
// 调用量恒=全量、无信息量，单列避免淹没按需类的频次）。

struct SkillInfo: Codable, Identifiable, Equatable {
    let name: String
    let family: String          // engine / client / tool
    let description: String
    let resident: Bool
    let targetsOk: Int
    let targetsTotal: Int
    let lastModified: Int
    let uses: Int
    let lastUsedAt: Int
    let sessions: [SkillSessionUse]

    var id: String { name }

    enum CodingKeys: String, CodingKey {
        case name, family, description, resident, uses, sessions
        case targetsOk = "targets_ok", targetsTotal = "targets_total"
        case lastModified = "last_modified", lastUsedAt = "last_used_at"
    }
}

struct SkillSessionUse: Codable, Equatable {
    let session: String
    let count: Int
}

// MARK: - Dashboard（wf_e86d52c97b51，GET /api/stats/dashboard）

struct DashboardStats: Codable, Equatable {
    struct TokenDay: Codable, Equatable {
        let day: String
        let inputTokens: Double
        let outputTokens: Double
        /// z.ai 口径（wf_5160b09e18d2）：缓存命中 token——命中率趋势图数据源。
        let cachedTokens: Double?
        let calls: Int
    }
    struct TokenToday: Codable, Equatable {
        let inputTokens: Double
        let outputTokens: Double
        /// z.ai 口径（wf_66a9b632154d）：缓存命中 token（input 子集）；旧端点缺键 nil。
        let cachedTokens: Double?
        let calls: Int
    }
    struct TokenYesterday: Codable, Equatable {
        let inputTokens: Double
        let outputTokens: Double
        let cachedTokens: Double?
    }
    struct Tokens: Codable, Equatable {
        let today: TokenToday
        let yesterday: TokenYesterday
        let byDay: [TokenDay]
    }
    struct WorkflowDay: Codable, Equatable {
        let day: String
        let count: Int
    }
    struct WorkflowStatusCount: Codable, Equatable {
        let status: String
        let count: Int
    }
    struct Workflows: Codable, Equatable {
        let total: Int
        let today: Int
        let yesterday: Int
        let byDay: [WorkflowDay]
        let byStatus: [WorkflowStatusCount]
    }
    /// 归属率（2026-10-06 web 统计视图替代时新增）：账本全量 vs 单子归属量
    /// （每单 会话×agent 步窗口 的 claude_code 回合）。旧端点缺键 nil。
    struct Attribution: Codable, Equatable {
        struct Quant: Codable, Equatable {
            let calls: Int
            let inputTokens: Double
            let outputTokens: Double
        }
        struct WorkflowQuant: Codable, Equatable {
            let prompts: Int
            let inputTokens: Double
            let outputTokens: Double
        }
        let ledger: Quant
        let workflow: WorkflowQuant
        let unattributed: Quant
        let inputRate: Double
    }
    let days: Int
    let tokens: Tokens
    let workflows: Workflows
    let attribution: Attribution?
}

// GET /api/usage/stats（模型分布饼图）
struct UsageByModel: Codable, Equatable {
    struct ModelUsage: Codable, Equatable {
        let model: String
        let calls: Int
        let inputTokens: Double
        let outputTokens: Double
    }
    let totalCalls: Int
    let totalInputTokens: Double
    let totalOutputTokens: Double
    let byModel: [ModelUsage]
}
